In [3]:
# cross validation : Evaluating Model Performance
# Sometimes we get confused to pick best suitable algo for out datasets so cross validation is used 

# Opn-1 : All the datasets that are available use for both training and testing
# Opn-2 :  Split datasets into traing datasets and testing datasets ( train-test-split)
# Opn-3 :  K-fold: the dataset is split into a K number of folds and is used to evaluate the model's ability when given new data. 
# K refers to the number of groups the data sample is split into.

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
from sklearn.datasets import load_digits


digits = load_digits()


In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [15]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\RUDRANARAYAN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [17]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9851851851851852

In [19]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

In [23]:
############################################
#####   K_FOLD #################
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
## n_splits is the no of folds 
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
for train_index , test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [27]:
# function to calculate score 
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [29]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\RUDRANARAYAN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [31]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9851851851851852

In [33]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9722222222222222

In [35]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)


In [65]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=30),X_train,X_test,y_train,y_test))

C:\Users\RUDRANARAYAN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\RUDRANARAYAN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

In [51]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [69]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [67]:
scores_rf

[0.9215358931552587, 0.9482470784641068, 0.9131886477462438]

In [75]:
from sklearn.model_selection import cross_val_score


In [77]:
cross_val_score (LogisticRegression(),digits.data,digits.target)

C:\Users\RUDRANARAYAN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\RUDRANARAYAN\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regres

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [79]:
cross_val_score (SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [83]:
cross_val_score (RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.91388889, 0.88333333, 0.95821727, 0.95543175, 0.91086351])

In [85]:
cross_val_score (RandomForestClassifier(n_estimators=5),digits.data,digits.target)


array([0.88333333, 0.80555556, 0.90529248, 0.90529248, 0.84401114])

In [89]:
cross_val_score (RandomForestClassifier(n_estimators=60),digits.data,digits.target)


array([0.93611111, 0.89166667, 0.96935933, 0.95543175, 0.92200557])